kind: Service
apiVersion: v1
metadata:
  name: go-debug-svc
spec:
  type: NodePort
  selector:
    app: go-debug
  ports:
    - name: app
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: dlv
      port: 2345
      targetPort: 2345
      nodePort: 32345
---
apiVersion: v1
kind: Pod
metadata:
  name: go-debug
  labels:
    app: go-debug
spec:
    containers:
    - name: go-debug
      image: go-app:debug
      command: ['dlv']
      args: ["debug", "local/myorg/myapp", "--listen=0.0.0.0:2345", "--headless=true", "--log=true"]
      ports:
      - containerPort: 8080
        protocol: TCP
      - containerPort: 2345
        protocol: TCP